- hosts: all
  sudo: true

  vars_files:
    - vars/vars.yml

  tasks:
    #- name: update yum packages
      #yum: name=* state=latest
    #- name: Install Dependencies
      #yum: pkg={{ item }}
      #with_items:
        #- gcc
        #- make
    #- name: install Git
      #yum: name=git state=present
    #- name: install Ruby
      #yum: name=ruby state=present
  roles:
    - role: user
    - role: nodejs
    #- role: vim
