---
- name: install Vim
  yum: name=vim state=present
- name: Download Vim Custom Settings & Plugins
  get_url: url=https://www.dropbox.com/s/c7a13h7yjhjk547/vim.tar.gz?dl=1
           dest=/root/vim.tar.gz
- name: Extract Source
  shell: cd ~/; tar xf vim.tar.gz
